### ISSUE TITLE
Local run error, help needed 

### ISSUE THREAD

**Issue by jugaldb** [abhishekvispute/paaradarshak-chainrunner#2]
Hey @abhishekvispute , thanks for replying, I am new to matic and blockchain in general, I was able to generate the mnemonic using metamask but am facing some issues in running truffle develop, I get the following error while running the
truffle develop command

Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
I hope you can help me sort this out, I know this is an old project of yours, but it would be great if you could help me out, thanks

It would be really really great if we can arrange a time for a google meet call and you can get me up and running, I am sure it wont take a lot of your time.

Thanks

**Comment by abhishekvispute** [comment]
Hey Hi 
@jugaldb
You don't need a mnemonic for the local net

Please paste the following default-config in truffle-config

```
const path = require("path");

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  contracts_build_directory: path.join(__dirname, "client/src/contracts"),
  networks: {
    develop: {
      port: 8545
    }
  }
};
```

and do 

>> truffle develop
Will list 10 default accounts
![image](https://user-images.githubusercontent.com/46760063/101978061-305bd980-3c78-11eb-9eb6-83e820366a88.png)

>> migrate
![image](https://user-images.githubusercontent.com/46760063/101978067-3b166e80-3c78-11eb-91f8-a938027c7a04.png)

In metamask add your local net rpc
![image](https://user-images.githubusercontent.com/46760063/101978048-14583800-3c78-11eb-8116-e8ec45802aaf.png)

import account using the private key
and you are good to go!

Thanks
